// Autogenerated file, don't edit anything
#pragma once

#define __ALLOW_ASSET_MACRO_INCLUDE__
#include <assets/macro.hpp>

#define FONT_FONT_TTF font_font_ttf
#define ICON_BMP icon_bmp
#define SOUND_RELOAD_WAV sound_reload_wav
#define SOUND_WIND_WAV sound_wind_wav
#define SPRITE_BACKGROUND_BACK_PNG sprite_background_back_png
#define SPRITE_BACKGROUND_FRONT_PNG sprite_background_front_png
#define SPRITE_COLOR_SCREEN_BLACK_PNG sprite_color_screen_black_png
#define SPRITE_FLORA_FLOWER1_PNG sprite_flora_flower1_png
#define SPRITE_FLORA_FLOWER2_PNG sprite_flora_flower2_png
#define SPRITE_FLORA_FLOWER3_PNG sprite_flora_flower3_png
#define SPRITE_FLORA_FLOWER4_PNG sprite_flora_flower4_png
#define SPRITE_FLORA_GRASS_PNG sprite_flora_grass_png
#define SPRITE_FLORA_SMALLROCK1_PNG sprite_flora_smallrock1_png
#define SPRITE_FLORA_SMALLROCK2_PNG sprite_flora_smallrock2_png
#define SPRITE_FLORA_SMALLROCK3_PNG sprite_flora_smallrock3_png
#define SPRITE_PLAYER_PLAYER_PNG sprite_player_player_png
#define SPRITE_ROAD_ROAD_PNG sprite_road_road_png
#define SPRITE_SCALE_ARROW_PNG sprite_scale_arrow_png
#define SPRITE_SCALE_SCALE_PNG sprite_scale_scale_png

INCBIN_EXTERN_MULTIPLE(
    (FONT_FONT_TTF)
    (ICON_BMP)
    (SOUND_RELOAD_WAV)
    (SOUND_WIND_WAV)
    (SPRITE_BACKGROUND_BACK_PNG)
    (SPRITE_BACKGROUND_FRONT_PNG)
    (SPRITE_COLOR_SCREEN_BLACK_PNG)
    (SPRITE_FLORA_FLOWER1_PNG)
    (SPRITE_FLORA_FLOWER2_PNG)
    (SPRITE_FLORA_FLOWER3_PNG)
    (SPRITE_FLORA_FLOWER4_PNG)
    (SPRITE_FLORA_GRASS_PNG)
    (SPRITE_FLORA_SMALLROCK1_PNG)
    (SPRITE_FLORA_SMALLROCK2_PNG)
    (SPRITE_FLORA_SMALLROCK3_PNG)
    (SPRITE_PLAYER_PLAYER_PNG)
    (SPRITE_ROAD_ROAD_PNG)
    (SPRITE_SCALE_ARROW_PNG)
    (SPRITE_SCALE_SCALE_PNG)
)
