// Autogenerated file, don't edit anything
#include <assets/assets.hpp>

INCBIN_MULTIPLE(
    (FONT_FONT_TTF, "font/font.ttf")
    (ICON_BMP, "icon.bmp")
    (SOUND_RELOAD_WAV, "sound/reload.wav")
    (SOUND_WIND_WAV, "sound/wind.wav")
    (SPRITE_BACKGROUND_BACK_PNG, "sprite/background/back.png")
    (SPRITE_BACKGROUND_FRONT_PNG, "sprite/background/front.png")
    (SPRITE_COLOR_SCREEN_BLACK_PNG, "sprite/color_screen/black.png")
    (SPRITE_FLORA_FLOWER1_PNG, "sprite/flora/flower1.png")
    (SPRITE_FLORA_FLOWER2_PNG, "sprite/flora/flower2.png")
    (SPRITE_FLORA_FLOWER3_PNG, "sprite/flora/flower3.png")
    (SPRITE_FLORA_FLOWER4_PNG, "sprite/flora/flower4.png")
    (SPRITE_FLORA_GRASS_PNG, "sprite/flora/grass.png")
    (SPRITE_FLORA_SMALLROCK1_PNG, "sprite/flora/smallrock1.png")
    (SPRITE_FLORA_SMALLROCK2_PNG, "sprite/flora/smallrock2.png")
    (SPRITE_FLORA_SMALLROCK3_PNG, "sprite/flora/smallrock3.png")
    (SPRITE_PLAYER_PLAYER_PNG, "sprite/player/player.png")
    (SPRITE_ROAD_ROAD_PNG, "sprite/road/road.png")
    (SPRITE_SCALE_ARROW_PNG, "sprite/scale/arrow.png")
    (SPRITE_SCALE_SCALE_PNG, "sprite/scale/scale.png")
)
