// Autogenerated file, don't edit anything
#include <assets/assets.hpp>

INCBIN(FONT_FONT_TTF, "font/font.ttf");
INCBIN(ICON_BMP, "icon.bmp");
INCBIN(ICON_ICO, "icon.ico");
INCBIN(SOUND_RELOAD_WAV, "sound/reload.wav");
INCBIN(SOUND_WIND_WAV, "sound/wind.wav");
INCBIN(SPRITE_BACKGROUND_BACK_PNG, "sprite/background/back.png");
INCBIN(SPRITE_BACKGROUND_FRONT_PNG, "sprite/background/front.png");
INCBIN(SPRITE_COLOR_SCREEN_BLACK_PNG, "sprite/color_screen/black.png");
INCBIN(SPRITE_DECOR_FLOWER1_PNG, "sprite/decor/flower1.png");
INCBIN(SPRITE_DECOR_FLOWER2_PNG, "sprite/decor/flower2.png");
INCBIN(SPRITE_DECOR_FLOWER3_PNG, "sprite/decor/flower3.png");
INCBIN(SPRITE_DECOR_FLOWER4_PNG, "sprite/decor/flower4.png");
INCBIN(SPRITE_DECOR_GRASS_PNG, "sprite/decor/grass.png");
INCBIN(SPRITE_DECOR_SMALLROCK1_PNG, "sprite/decor/smallrock1.png");
INCBIN(SPRITE_DECOR_SMALLROCK2_PNG, "sprite/decor/smallrock2.png");
INCBIN(SPRITE_DECOR_SMALLROCK3_PNG, "sprite/decor/smallrock3.png");
INCBIN(SPRITE_PLAYER_PLAYER_PNG, "sprite/player/player.png");
INCBIN(SPRITE_ROAD_ROAD_PNG, "sprite/road/road.png");
INCBIN(SPRITE_SCALE_ARROW_PNG, "sprite/scale/arrow.png");
INCBIN(SPRITE_SCALE_SCALE_PNG, "sprite/scale/scale.png");
